/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testpostweb;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class PostWebManual extends javax.swing.JFrame {
    private static HttpURLConnection con;
    
    /**
     * Creates new form PostWebManual
     */
    public PostWebManual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaURL = new javax.swing.JTextArea();
        lblPatientID6 = new javax.swing.JLabel();
        lblPatientID8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaPostData = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaPostDataEncode = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResult = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaContent = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaParameter = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1171, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Post json");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 137, 30));

        txaURL.setColumns(20);
        txaURL.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txaURL.setRows(5);
        jScrollPane5.setViewportView(txaURL);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 13, 1000, 68));

        lblPatientID6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID6.setText("Content-Type");
        getContentPane().add(lblPatientID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 88, 127, 37));

        lblPatientID8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID8.setText("Parameter");
        getContentPane().add(lblPatientID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 131, 127, 38));

        txaPostData.setColumns(20);
        txaPostData.setLineWrap(true);
        txaPostData.setRows(5);
        jScrollPane3.setViewportView(txaPostData);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 480, 170));

        txaPostDataEncode.setColumns(20);
        txaPostDataEncode.setLineWrap(true);
        txaPostDataEncode.setRows(5);
        jScrollPane4.setViewportView(txaPostDataEncode);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 480, 170));

        txaResult.setColumns(20);
        txaResult.setLineWrap(true);
        txaResult.setRows(5);
        jScrollPane1.setViewportView(txaResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 286, 660, 350));

        txaContent.setColumns(20);
        txaContent.setRows(5);
        jScrollPane2.setViewportView(txaContent);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 1000, 40));

        txaParameter.setColumns(20);
        txaParameter.setRows(5);
        jScrollPane6.setViewportView(txaParameter);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 1000, 140));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Post json V2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 137, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String sPatientID;
        String sType;
        String sTitle;
        String sDescription;
        String sImage;
        String sDataDate;
        String sGroupHN;
        String sContentType;
        String sDoctorID;
        String sStationCode;
        String sQueueNumber;
        String sStationNameTH;
        String sStationNameEN;
        String urlParameters;
        
        // https://httpbin.org/post         https://rkh-srvapp-ramgroup.southeastasia.cloudapp.azure.com:5905/api/upload/rmdr
        // http://10.100.212.184:8080/InterfaceServer/PublishReminder
        String sParameter = txaParameter.getText();
        String sURL = txaURL.getText();

        /*
            http://httpbin.org/post
            application/x-www-form-urlencoded
            param3=345&param4=ert        
        
            https://httpbin.org/post
            application/x-www-form-urlencoded
            name=John Doe&occupation=gardener
        
            application/json; charset=UTF-8
        */
        
        // name=Jack&occupation=programmer
        // sHTMLActivitiesTemplate = sHTMLActivitiesTemplate.replace("@NRS_TEMP", sHTMLSubTagNUR);
        // @JSON_HEADER&@JSON_PATIENT_ID&@JSON_TYPE&@JSON_TITLE&@JSON_DESC&@JSON_IMAGE&@JSON_DATE&@JSON_GROUP
        // @JSON_UPD_DTTM   yyyy-MM-DD	hh:mm:ss.sss  2019-01-01 10:00:00.000
        // [{@JSON_DOC_ID,@JSON_CURR_POS,@JSON_UPD_DTTM}]
        //// [{@JSON_DOC_ID,@JSON_DOC_HOURS,@JSON_USER_HN,@JSON_USER_POS,@JSON_STN_CD,@JSON_STN_NAME_TH,@JSON_STN_NAME_EN,@JSON_UPD_DTTM}]
        // [{@JSON_DOC_ID,@JSON_DOC_HOURS,@JSON_USER_HN,@JSON_USER_POS,@JSON_STN_CD,@JSON_STN_NAME_TH,@JSON_STN_NAME_EN,@JSON_UPD_TYPE,@JSON_UPD_DTTM}]
        // application/x-www-form-urlencoded
        sContentType = txaContent.getText();

        urlParameters = sParameter;

        txaPostData.setText(urlParameters);
        /*
        try {
            urlParameters = URLEncoder.encode(urlParameters, "UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        txaPostDataEncode.setText(urlParameters);

        
        
        byte[] postData = urlParameters.getBytes(StandardCharsets.UTF_8);       // StandardCharsets.UTF_8

        int postDataLength = postData.length;

        try {

            URL myurl = null;
            try {
                myurl = new URL(sURL);
            } catch (MalformedURLException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                con = (HttpURLConnection) myurl.openConnection();
                //HttpURLConnection con = (HttpURLConnection) myurl.openConnection();
            } catch (IOException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }

            con.setConnectTimeout(5000);
            con.setDoInput(true);
            
            con.setDoOutput(true);
            con.setInstanceFollowRedirects(false);
            try {
                con.setRequestMethod("POST");       // POST  GET
            } catch (ProtocolException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }
            con.setRequestProperty("Content-Type", sContentType + "; charset=UTF-8");
            con.setRequestProperty("Accept-Charset", "UTF-8");
            con.setRequestProperty("Content-Length", Integer.toString(postDataLength ));
            con.setUseCaches(false);
            //con.setRequestProperty("User-Agent", "Java client");

            try (DataOutputStream wr = new DataOutputStream(con.getOutputStream())) {
                wr.write(postData);
            } catch (IOException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }

            StringBuilder content = null;

            try (BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()))) {

            String line;
            content = new StringBuilder();

            while ((line = in.readLine()) != null) {
                content.append(line);
                content.append(System.lineSeparator());
            }
        } catch (IOException ex) {
            Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
        }

        String sReturnResult = "";
        sReturnResult = content.toString();

        txaResult.append(sReturnResult);

        // System.out.println(content.toString());

        } finally {

            con.disconnect();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sNum;
        String sNum2;
        String sCod;
        String sAll;
        
        sNum = "1";
        sNum2 = "0000" + sNum;
        sCod = "DEP";
        sAll = sCod + sNum2.substring(sNum2.length() - 3) ;
                
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostWebManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostWebManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostWebManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostWebManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostWebManual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblPatientID6;
    private javax.swing.JLabel lblPatientID8;
    private javax.swing.JTextArea txaContent;
    private javax.swing.JTextArea txaParameter;
    private javax.swing.JTextArea txaPostData;
    private javax.swing.JTextArea txaPostDataEncode;
    private javax.swing.JTextArea txaResult;
    private javax.swing.JTextArea txaURL;
    // End of variables declaration//GEN-END:variables
}
