/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testpostweb;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;


import org.w3c.dom.Node;
import org.w3c.dom.bootstrap.DOMImplementationRegistry;
import org.w3c.dom.ls.DOMImplementationLS;
import org.w3c.dom.ls.LSSerializer;
import org.xml.sax.InputSource;

import javax.xml.parsers.DocumentBuilderFactory;


/**
 *
 * @author sithitat.s
 */
public class PostWeb extends javax.swing.JFrame {
    
    private static HttpURLConnection con;
    
    /**
     * Creates new form PostWeb
     */
    public PostWeb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResult = new javax.swing.JTextArea();
        lblPatientID = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        lblPatientID1 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        lblPatientID2 = new javax.swing.JLabel();
        txtTitleTH = new javax.swing.JTextField();
        txtTitleEN = new javax.swing.JTextField();
        lblPatientID3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        lblPatientID4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblPatientID5 = new javax.swing.JLabel();
        txtGroup = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaPostData = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaPostDataEncode = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaURL = new javax.swing.JTextArea();
        lblPatientID6 = new javax.swing.JLabel();
        txtContentType = new javax.swing.JTextField();
        lblDoctorID = new javax.swing.JLabel();
        txtHeader = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblPatientID8 = new javax.swing.JLabel();
        txtDoctorID = new javax.swing.JTextField();
        txtQueNum = new javax.swing.JTextField();
        txtStationCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("Post json");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txaResult.setColumns(20);
        txaResult.setLineWrap(true);
        txaResult.setRows(5);
        jScrollPane1.setViewportView(txaResult);

        lblPatientID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID.setText("Type");

        txtType.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtType.setText("type=event");

        lblPatientID1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID1.setText("Patient ID");

        txtPatientID.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N

        lblPatientID2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID2.setText("Title");

        txtTitleTH.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtTitleTH.setText("title_TH=สถานะของผู้ป่วย");

        txtTitleEN.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtTitleEN.setText("title_EN=Patient Status");

        lblPatientID3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID3.setText("Description");

        txaDescription.setColumns(20);
        txaDescription.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txaDescription.setRows(5);
        txaDescription.setText("<H4>Patient Status / สถานะของผู้ป่วย</H4>");
        jScrollPane2.setViewportView(txaDescription);

        lblPatientID4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID4.setText("Date");

        txtDate.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtDate.setText("data={\"date\":\"2019-04-28\", \"time\":\"13:13\"}");

        lblPatientID5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID5.setText("Group");

        txtGroup.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtGroup.setText("group_list=[]&hn_list=[\"900003\"]");

        txaPostData.setColumns(20);
        txaPostData.setLineWrap(true);
        txaPostData.setRows(5);
        jScrollPane3.setViewportView(txaPostData);

        txaPostDataEncode.setColumns(20);
        txaPostDataEncode.setLineWrap(true);
        txaPostDataEncode.setRows(5);
        jScrollPane4.setViewportView(txaPostDataEncode);

        txaURL.setColumns(20);
        txaURL.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txaURL.setRows(5);
        jScrollPane5.setViewportView(txaURL);

        lblPatientID6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID6.setText("Content-Type");

        txtContentType.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtContentType.setText("application/x-www-form-urlencoded");

        lblDoctorID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDoctorID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDoctorID.setText("Doctor ID");

        txtHeader.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtHeader.setText("hn=999999&pass=123456&hosp_id=RKH&process=upsert&auth=Patient");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setText("Parsers XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblPatientID8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPatientID8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID8.setText("Header");

        txtDoctorID.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N

        txtQueNum.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtQueNum.setText("Queue No.");

        txtStationCode.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        txtStationCode.setText("Station Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPatientID5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGroup))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPatientID4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDate))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPatientID3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPatientID1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTitleEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblPatientID2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTitleTH, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtStationCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPatientID6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPatientID8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtQueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                                            .addComponent(txtContentType, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatientID6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(lblPatientID8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtContentType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTitleTH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPatientID2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPatientID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitleEN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPatientID3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientID4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientID5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String sPatientID;
        String sType;
        String sTitle;
        String sDescription;
        String sImage;
        String sDataDate;
        String sGroupHN;
        String sContentType;
        String sDoctorID;
        String sStationCode;
        String sQueueNumber;
        String sStationNameTH;
        String sStationNameEN;
        
        // https://httpbin.org/post         https://rkh-srvapp-ramgroup.southeastasia.cloudapp.azure.com:5905/api/upload/rmdr
        // http://10.100.212.184:8080/InterfaceServer/PublishReminder
        String sHeader = txtHeader.getText();
        String sURL = txaURL.getText();
        String sImageURL = "https://rkh-srvapp-ramgroup.southeastasia.cloudapp.azure.com:5905/upload/images/eeb944b724a3a58f3ea4a05ad3d8c9c4";
        
        // name=Jack&occupation=programmer
        // sHTMLActivitiesTemplate = sHTMLActivitiesTemplate.replace("@NRS_TEMP", sHTMLSubTagNUR);
        // @JSON_HEADER&@JSON_PATIENT_ID&@JSON_TYPE&@JSON_TITLE&@JSON_DESC&@JSON_IMAGE&@JSON_DATE&@JSON_GROUP
        // @JSON_UPD_DTTM   yyyy-MM-DD	hh:mm:ss.sss  2019-01-01 10:00:00.000
        // [{@JSON_DOC_ID,@JSON_CURR_POS,@JSON_UPD_DTTM}]
        //// [{@JSON_DOC_ID,@JSON_DOC_HOURS,@JSON_USER_HN,@JSON_USER_POS,@JSON_STN_CD,@JSON_STN_NAME_TH,@JSON_STN_NAME_EN,@JSON_UPD_DTTM}]
        // [{@JSON_DOC_ID,@JSON_DOC_HOURS,@JSON_USER_HN,@JSON_USER_POS,@JSON_STN_CD,@JSON_STN_NAME_TH,@JSON_STN_NAME_EN,@JSON_UPD_TYPE,@JSON_UPD_DTTM}]
        String urlParameters = "{@JSON_HEADER,@JSON_POST_LIST}";
        String urlPostList = "[{@JSON_DOC_ID,@JSON_DOC_HOURS,@JSON_USER_HN,@JSON_USER_POS,@JSON_STN_CD,@JSON_STN_NAME_TH,@JSON_STN_NAME_EN,@JSON_UPD_TYPE,@JSON_UPD_DTTM}]";
        
        sContentType = txtContentType.getText();
        
        urlParameters = urlParameters.replace("@JSON_HEADER", sHeader);
        
        sPatientID = txtPatientID.getText();
        // urlParameters = urlParameters.replace("@JSON_PATIENT_ID", sPatientID);      
        urlPostList = urlPostList.replace("@JSON_USER_HN", sPatientID);      
        
        sDoctorID = txtDoctorID.getText();
        urlPostList = urlPostList.replace("@JSON_DOC_ID", sDoctorID);
        
        sQueueNumber = txtQueNum.getText();
        urlPostList = urlPostList.replace("@JSON_USER_POS", sQueueNumber);
        
        sStationCode = txtStationCode.getText();
        urlPostList = urlPostList.replace("@JSON_STN_CD", sStationCode);
        
        sType = txtType.getText();
        // urlParameters = urlParameters.replace("@JSON_TYPE", sType);
        urlPostList = urlPostList.replace("@JSON_CURR_POS", sType);
        urlPostList = urlPostList.replace("@JSON_DOC_HOURS", sType);
        
        sTitle = txtTitleTH.getText() + "&" + txtTitleEN.getText();
        sStationNameTH = txtTitleTH.getText();
        urlPostList = urlPostList.replace("@JSON_STN_NAME_TH", sStationNameTH);
        
        sStationNameEN = txtTitleEN.getText();
        urlPostList = urlPostList.replace("@JSON_STN_NAME_EN", sStationNameEN);
        
        // urlParameters = urlParameters.replace("@JSON_TITLE", sTitle);
        urlParameters = urlParameters.replace("@JSON_STN_NAME_TH", sTitle);
        
        sDescription = "desc_TH=" + txaDescription.getText();
        sDescription = sDescription + "&desc_EN=" + txaDescription.getText();
        urlParameters = urlParameters.replace("@JSON_DESC", sDescription);
        urlParameters = urlParameters.replace("@JSON_STN_NAME_EN", sTitle);
        
        sImage = "img_TH_url=" + sImageURL;
        sImage = sImage + "&img_EN_url=" + sImageURL;
        urlParameters = urlParameters.replace("@JSON_IMAGE", sImage);
        
        urlPostList = urlPostList.replace("@JSON_UPD_TYPE", "\"upd_type\":\"upsert\"");
        
        sDataDate = txtDate.getText();
        // urlParameters = urlParameters.replace("@JSON_DATE", sDataDate);
        urlPostList = urlPostList.replace("@JSON_UPD_DTTM", sDataDate);
        
        sGroupHN = txtGroup.getText();
        urlParameters = urlParameters.replace("@JSON_GROUP", sGroupHN);        
        
        // curr_pos_list        user_pos_list
        urlParameters = urlParameters.replace("@JSON_POST_LIST", "\"user_pos_list\":" + urlPostList);        
        
        //urlParameters = "hn=999999&pass=123456&hosp_id=RKH&process=upsert&auth=Patient&id=PATATV-900003-201904281313&type=event&title_TH=สถานะของผู้ป่วย&title_EN=Patient Status";
        
        //urlParameters = urlParameters + "&desc_TH=<H4>Patient Status / สถานะของผู้ป่วย</H4><br><table border=\"1\" width=\"400\" align=\"center\"><tr><td colspan=\"2\" width=\"100%\" height=\"50\" align=\"center\" valign=\"center\"><font color=\"#000080\"><span class=\"headd\"><strong>HN:900003 MR.TEST SYSTEM</strong></span></font></td> </tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">P</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Register</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">P</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Meet Nurse</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">P</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Meet Doctor</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">W</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Payment Complete</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">W</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Receive Medicine</td></tr></table>";
        //urlParameters = urlParameters + "&desc_EN=<H4>Patient Status / สถานะของผู้ป่วย</H4><br><table border=\"1\" width=\"400\" align=\"center\"><tr><td colspan=\"2\" width=\"100%\" height=\"50\" align=\"center\" valign=\"center\"><font color=\"#000080\"><span class=\"headd\"><strong>HN:900003 MR.TEST SYSTEM</strong></span></font></td> </tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">P</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Register</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">P</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Meet Nurse</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">P</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Meet Doctor</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">W</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Payment Complete</td></tr><tr bgcolor=\"#F9FBFF\"><td width=\"20%\" height=\"50\" align=\"center\" valign=\"center\">W</td><td width=\"80%\" height=\"50\" align=\"Left\" valign=\"center\">Receive Medicine</td></tr></table>";
        //urlParameters = urlParameters + "&desc_TH=<H4>Patient Status / สถานะของผู้ป่วย</H4>";
        //urlParameters = urlParameters + "&desc_EN=<H4>Patient Status / สถานะของผู้ป่วย</H4>";
        
        //urlParameters = urlParameters + "&" + sDescription;
        //urlParameters = urlParameters + "&img_TH_url=https://rkh-srvapp-ramgroup.southeastasia.cloudapp.azure.com:5905/upload/images/eeb944b724a3a58f3ea4a05ad3d8c9c4";
        //urlParameters = urlParameters + "&img_EN_url=https://rkh-srvapp-ramgroup.southeastasia.cloudapp.azure.com:5905/upload/images/eeb944b724a3a58f3ea4a05ad3d8c9c4";
        //urlParameters = urlParameters + "&data={\"date\":\"2019-04-28\", \"time\":\"13:13\"}";
        //urlParameters = urlParameters + "&group_list=[]&hn_list=[\"900003\"]";
        txaPostData.setText(urlParameters);
        /*
        try {
            urlParameters = URLEncoder.encode(urlParameters, "UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        txaPostDataEncode.setText(urlParameters);
        
        byte[] postData = urlParameters.getBytes(StandardCharsets.UTF_8);       // StandardCharsets.UTF_8

        int postDataLength = postData.length;
        
        try {

            URL myurl = null;
            try {
                myurl = new URL(sURL);
            } catch (MalformedURLException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                con = (HttpURLConnection) myurl.openConnection();
                //HttpURLConnection con = (HttpURLConnection) myurl.openConnection();
            } catch (IOException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }

            con.setDoOutput(true);
            con.setInstanceFollowRedirects(false);
            try {
                con.setRequestMethod("POST");
            } catch (ProtocolException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }
            con.setRequestProperty("Content-Type", sContentType + "; charset=UTF-8");
            con.setRequestProperty("Accept-Charset", "UTF-8");
            con.setRequestProperty("Content-Length", Integer.toString(postDataLength ));
            con.setUseCaches(false);
            //con.setRequestProperty("User-Agent", "Java client");
            

            try (DataOutputStream wr = new DataOutputStream(con.getOutputStream())) {
                wr.write(postData);
            } catch (IOException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }

            StringBuilder content = null;

            try (BufferedReader in = new BufferedReader(
                    new InputStreamReader(con.getInputStream()))) {

                String line;
                content = new StringBuilder();

                while ((line = in.readLine()) != null) {
                    content.append(line);
                    content.append(System.lineSeparator());
                }
            } catch (IOException ex) {
                Logger.getLogger(PostWeb.class.getName()).log(Level.SEVERE, null, ex);
            }

            String sReturnResult = "";
            sReturnResult = content.toString();

            txaResult.append(sReturnResult);
            
            // System.out.println(content.toString());

        } finally {
            
            con.disconnect();
        }      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ParsersXML().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostWeb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientID1;
    private javax.swing.JLabel lblPatientID2;
    private javax.swing.JLabel lblPatientID3;
    private javax.swing.JLabel lblPatientID4;
    private javax.swing.JLabel lblPatientID5;
    private javax.swing.JLabel lblPatientID6;
    private javax.swing.JLabel lblPatientID8;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JTextArea txaPostData;
    private javax.swing.JTextArea txaPostDataEncode;
    private javax.swing.JTextArea txaResult;
    private javax.swing.JTextArea txaURL;
    private javax.swing.JTextField txtContentType;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtGroup;
    private javax.swing.JTextField txtHeader;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtQueNum;
    private javax.swing.JTextField txtStationCode;
    private javax.swing.JTextField txtTitleEN;
    private javax.swing.JTextField txtTitleTH;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
